# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.4/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/panda/Desktop/qt_project/TKA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/panda/Desktop/qt_project/TKA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/panda/Desktop/qt_project/TKA/CMakeFiles /Users/panda/Desktop/qt_project/TKA//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/panda/Desktop/qt_project/TKA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TKA

# Build rule for target.
TKA: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TKA
.PHONY : TKA

# fast build rule for target.
TKA/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/build
.PHONY : TKA/fast

#=============================================================================
# Target rules for targets named TKA_autogen

# Build rule for target.
TKA_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TKA_autogen
.PHONY : TKA_autogen

# fast build rule for target.
TKA_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA_autogen.dir/build.make CMakeFiles/TKA_autogen.dir/build
.PHONY : TKA_autogen/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

playcontroler.o: playcontroler.cpp.o
.PHONY : playcontroler.o

# target to build an object file
playcontroler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/playcontroler.cpp.o
.PHONY : playcontroler.cpp.o

playcontroler.i: playcontroler.cpp.i
.PHONY : playcontroler.i

# target to preprocess a source file
playcontroler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/playcontroler.cpp.i
.PHONY : playcontroler.cpp.i

playcontroler.s: playcontroler.cpp.s
.PHONY : playcontroler.s

# target to generate assembly for a file
playcontroler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/playcontroler.cpp.s
.PHONY : playcontroler.cpp.s

player.o: player.cpp.o
.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i
.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s
.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/player.cpp.s
.PHONY : player.cpp.s

threedimage.o: threedimage.cpp.o
.PHONY : threedimage.o

# target to build an object file
threedimage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/threedimage.cpp.o
.PHONY : threedimage.cpp.o

threedimage.i: threedimage.cpp.i
.PHONY : threedimage.i

# target to preprocess a source file
threedimage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/threedimage.cpp.i
.PHONY : threedimage.cpp.i

threedimage.s: threedimage.cpp.s
.PHONY : threedimage.s

# target to generate assembly for a file
threedimage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/threedimage.cpp.s
.PHONY : threedimage.cpp.s

videodlg.o: videodlg.cpp.o
.PHONY : videodlg.o

# target to build an object file
videodlg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/videodlg.cpp.o
.PHONY : videodlg.cpp.o

videodlg.i: videodlg.cpp.i
.PHONY : videodlg.i

# target to preprocess a source file
videodlg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/videodlg.cpp.i
.PHONY : videodlg.cpp.i

videodlg.s: videodlg.cpp.s
.PHONY : videodlg.s

# target to generate assembly for a file
videodlg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TKA.dir/build.make CMakeFiles/TKA.dir/videodlg.cpp.s
.PHONY : videodlg.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TKA_autogen"
	@echo "... TKA"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... playcontroler.o"
	@echo "... playcontroler.i"
	@echo "... playcontroler.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... threedimage.o"
	@echo "... threedimage.i"
	@echo "... threedimage.s"
	@echo "... videodlg.o"
	@echo "... videodlg.i"
	@echo "... videodlg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

